if (WIN32)
    set(JDKRIG_OS_WIN ON)
elseif (APPLE)
    set(JDKRIG_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(JDKRIG_OS_IOS ON)
    else()
        set(JDKRIG_OS_MACOS ON)
    endif()
else()
    set(JDKRIG_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(JDKRIG_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(JDKRIG_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD OR CMAKE_SYSTEM_NAME STREQUAL DragonFly)
        set(JDKRIG_OS_FREEBSD ON)
    endif()
endif()


if (JDKRIG_OS_WIN)
    add_definitions(-DWIN32 -DJDKRIG_OS_WIN)
elseif(JDKRIG_OS_APPLE)
    add_definitions(-DJDKRIG_OS_APPLE)

    if (JDKRIG_OS_IOS)
        add_definitions(-DJDKRIG_OS_IOS)
    else()
        add_definitions(-DJDKRIG_OS_MACOS)
    endif()

    if (JDKRIG_ARM)
        set(WITH_SECURE_JIT ON)
    endif()
elseif(JDKRIG_OS_UNIX)
    add_definitions(-DJDKRIG_OS_UNIX)

    if (JDKRIG_OS_ANDROID)
        add_definitions(-DJDKRIG_OS_ANDROID)
    elseif (JDKRIG_OS_LINUX)
        add_definitions(-DJDKRIG_OS_LINUX)
    elseif (JDKRIG_OS_FREEBSD)
        add_definitions(-DJDKRIG_OS_FREEBSD)
    endif()
endif()

if (WITH_SECURE_JIT)
    add_definitions(-DJDKRIG_SECURE_JIT)
endif()
